git-helper is meaty

diff --git a/bin/git-helper b/bin/git-helper
--- a/bin/git-helper
+++ b/bin/git-helper
@@ -1,22 +1,58 @@
-#!/bin/bash -e
+#!/bin/bash
 
-nm_helper=$1; shift
+#/ NAME
+#/     git-helper -- template for a meaty script
+#/
+#/ SYNOPSIS
+#/     git helper [helper_id]
+#/       where helper_id is
+#/          sh - bash shell meat library
+#/          ao - alpha_omega deploy commands
+#/          rb - rubygems development
+#/         tvd - microwave tvdinners
 
-case $nm_helper in
-  sh)
-    git remote add sh https://github.com/HeSYINUvSBZfxqA/meat
-    git fetch sh
-    ;;
-  ao)
-    git remote add ao https://github.com/HeSYINUvSBZfxqA/ao-helper
-    git fetch ao
-    ;;
-  rb)
-    git remote add rb https://github.com/HeSYINUvSBZfxqA/rb-helper
-    git fetch rb
-    ;;
-  tvd)
-    git remote add tvd https://github.com/HeSYINUvSBZfxqA/tvdinner
-    git fetch tvd
-    ;;
-esac
+# figure out the project root under which bin, lib live
+shome="$(cd -P -- "$(dirname -- "$0")/.." && pwd -P)"
+
+# load a meat library
+source "$shome/bin/_prime" "$@"
+
+# entry point
+function main {
+  nm_helper="$1"; shift
+
+  case "$nm_helper" in
+    sh)
+      git remote add sh https://github.com/HeSYINUvSBZfxqA/meat
+      git fetch sh
+      ;;
+    ao)
+      git remote add ao https://github.com/HeSYINUvSBZfxqA/ao-helper
+      git fetch ao
+      ;;
+    rb)
+      git remote add rb https://github.com/HeSYINUvSBZfxqA/rb-helper
+      git fetch rb
+      ;;
+    tvd)
+      git remote add tvd https://github.com/HeSYINUvSBZfxqA/tvdinner
+      git fetch tvd
+      ;;
+    *)
+      echo "ERROR: unknown helper $nm_helper" 1>&2
+      exit 1
+      ;;
+  esac
+}
+
+# parse the command-line
+parse_command_line "$@" || exit $?
+eval set -- "${FLAGS_ARGV}"
+if [[ "$#" = 0 ]]; then
+  echo "ERROR: must specify a helper_id" 1>&2
+  display_help
+  exit 4
+fi
+
+# pass arguments to entry point
+main "$@"
