clone proxy

diff --git a/bin/proxy b/bin/proxy
--- a/bin/proxy
+++ b/bin/proxy
@@ -11,45 +11,68 @@
 # figure out the project root under which bin, lib live
 shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
 
+function git_branch_head {
+  local ver_repo="$1"; shift
+
+  local git_branch
+  local git_head
+
+  if [[ "$ver_repo" != "HEAD" ]]; then
+    git_branch=""
+    git_head="$ver_repo"
+  else
+    local git_ref=$(cat $shome/.git/HEAD)
+    if echo "$git_ref" | egrep -q "^ref:"; then
+      git_branch=$(echo "$git_ref" | awk '{print $2}' | cut -d/ -f3-)
+      git_head=$(git show-ref --hash "$(echo "$git_ref" | awk '{print $2}')")
+    else
+      git_branch=""
+      git_head=$git_ref
+    fi
+  fi
+
+  if [[ -z $git_head ]]; then
+    echo "ERROR: could not find the SHA for HEAD" 1>&2
+    return 1
+  fi
+
+  echo "$git_branch:$git_head"
+}
+
+
+function clone_proxy {
+  local ver_repo=$2
+  export _AO_PROXIED=1
+  rm -rf $shome/.tmp/deploy
+  git clone -q $shome $shome/.tmp/deploy
+  cd $shome/.tmp/deploy
+  local git_head="$(git_branch_head "$ver_repo" | cut -d: -f2)"
+  git checkout -q $git_head
+  exec $shome/.tmp/deploy/bin/proxy "$@"
+}
+
+: ${_AO_PROXIED:=}
+if [[ -z "$_AO_PROXIED" ]]; then
+  clone_proxy "$@"
+fi
+
 # load a jason bourne library
 source "$shome/bin/_treadstone"
 
 # entry point
 function main {
-  local nm_component="$1"; shift
-  case "$nm_component" in 
+  local hst_gateway="$1"; shift
+  case "$hst_gateway" in 
     *)
-      local hst_proxy="$nm_component"
       local ver_repo="$1"; shift
 
-      # remote arguments
+      local git_spec="$(git_branch_head "$ver_repo")"
       local git_url="$(git config --list | grep remote.origin.url | cut -d= -f2-)"
-
-      local git_branch
-      local git_head
-
-      if [[ "$ver_repo" != "HEAD" ]]; then
-        git_branch=""
-        git_head="$ver_repo"
-      else
-        local git_ref=$(cat .git/HEAD)
-        if echo "$git_ref" | egrep -q "^ref:"; then
-          git_branch=$(echo "$git_ref" | awk '{print $2}' | cut -d/ -f3-)
-          git_head=$(git show-ref --hash "$(echo "$git_ref" | awk '{print $2}')")
-        else
-          git_branch=""
-          git_head=$git_ref
-        fi
-      fi
-
-      if [[ -z $git_head ]]; then
-        echo "ERROR: could not find the SHA for HEAD" 1>&2
-        exit 1
-      fi
 
       local pth_rvmrun="$(ruby -ryaml -e 'puts YAML.load(File.read(ARGV[0]))[ARGV[1]]' $shome/config/deploy.yml ruby_loader)"
       local nm_ruby="$(ruby -ryaml -e 'puts YAML.load(File.read(ARGV[0]))[ARGV[1]]' $shome/config/deploy.yml deploy_ruby)"
-      cat $shome/bin/remote-helper | ssh $hst_proxy "$pth_rvmrun" "$nm_ruby" bash -s "$USER" "$git_url" "$git_branch:$git_head" "$@"
+
+      cat $shome/bin/remote-helper | ssh $hst_gateway "$pth_rvmrun" "$nm_ruby" bash -s "$USER" "$git_url" "$git_spec" "$@"
       ;;
   esac
 }
