support push to a private geminabox

diff --git a/bin/push b/bin/push
--- a/bin/push
+++ b/bin/push
@@ -1,10 +1,11 @@
 #!/bin/bash
 
 #/ NAME
-#/     push -- upload the latest (timestamp) rubygem to rubygems.org
+#/     push -- push a gem to a local, remote rubygems,geminabox repository
 #/
 #/ SYNOPSIS
-#/     push gem
+#/     push --public gem
+#/     push [--local|--private|--public] [gem...]
 
 # figure out the project root under which bin, lib live
 shome="$(cd -P -- "$(dirname -- "$0")/.." && pwd -P)"
@@ -18,13 +19,26 @@ function main {
 
   case "$nm_component" in 
     gem)
-      push_gem "$@"
+      if [[ "$FLAGS_public" = "$FLAGS_TRUE" ]]; then
+        push_gem "$@"
+      else
+        logger_fatal "must specify --public to confirm a gem push to rubygems.org"
+        exit 1
+      fi
       ;;
     *)
-      logger_fatal "don't know how to build ${nm_component}"
-      exit 1
+      if [[ "$FLAGS_private" = "$FLAGS_TRUE" ]]; then
+        push_gem_private "$@"
+      else
+        fatal_logger "must specify --private to push to a private repository"
+      fi
       ;;
   esac
+}
+
+# push a gem locally 
+function push_gem_private {
+  gem inabox -g http://localhost:9292 "$@"
 }
 
 # push the latest gem to rubygems.org
@@ -43,13 +57,16 @@ function push_gem {
 
 # define command line options:
 #   var name, default, description, short option
+DEFINE_boolean "private" "$FLAGS_TRUE" "push to a local, private geminabox"
+DEFINE_boolean "shared" "$FLAGS_FALSE" "push to a shared, private geminabox"
+DEFINE_boolean "public" "$FLAGS_FALSE" "push to rubygems.org"
 
 # parse the command-line
 parse_command_line "$@" || exit $?
 eval set -- "${FLAGS_ARGV}"
 
 if [[ "$#" < 1 ]]; then
-  logger_fatal "missing component"
+  logger_fatal "missing component or gem(s)"
   exit 1
 fi
 
