remote-helper actually uses rvmrun

diff --git a/bin/remote-helper b/bin/remote-helper
--- a/bin/remote-helper
+++ b/bin/remote-helper
@@ -3,16 +3,11 @@
 pth_rvmrun="$1"; shift
 nm_ruby="$1"; shift
 
-if [[ ! -x $(which bundle 2>&1) ]]; then
-  if [[ -z $_AO_HELPER ]]; then
-    export _AO_HELPER=1
-    exec "$pth_rvmrun" "$nm_ruby" $0 "$pth_rvmrun" "$nm_ruby" "$@"
-    echo "ERROR: could not re-exec $0 under $pth_rvmrun $nm_ruby"
-    exit 1
-  else
-    echo "ERROR: could not find bundle after $pth_rvmrun $nm_ruby"
-    exit 1
-  fi
+if [[ -z $_AO_HELPER ]]; then
+  export _AO_HELPER=1
+  exec $0 "$@"
+  echo "ERROR: could not re-exec $0 under $pth_rvmrun $nm_ruby"
+  exit 1
 fi
 
 nm_deployer=$1; shift
