avoid remote mktemp, rsync, and exec

diff --git a/bin/remote-helper b/bin/remote-helper
--- a/bin/remote-helper
+++ b/bin/remote-helper
@@ -6,32 +6,33 @@ function crumb {
   fi
 }
 
-pth_rvmrun=
-nm_ruby="ree"
-
-if [[ -z $_AO_HELPER ]]; then
-  export _AO_HELPER=1
-  exec "$pth_rvmrun" "$nm_ruby" $0 "$@"
-  echo "ERROR: could not re-exec $0 under $pth_rvmrun $nm_ruby"
-  exit 1
-fi
-
-unset cd # disable rvm's cd function to prevent prompts
-
+pth_rvmrun=$1; shift
+nm_ruby=$1; shift
 nm_deployer=$1; shift
 git_url=$1; shift
 git_spec=$1; shift
-git_branch=$(echo $git_spec | cut -d: -f1)
-git_sha=$(echo $git_spec | cut -d: -f2)
-
 cmd_deploy=$1; shift
+
 if [[ "$cmd_deploy" = "debug" ]]; then
   fl_debug=1
 else
   fl_debug=
 fi
 
-crumb "starting debug"  
+if [[ -z $_AO_HELPER ]]; then
+  crumb "exec under $pth_rvmrun $nm_ruby $0 $pth_rvmrun $nm_ruby $nm_deployer $git_url $git_spec $cmd_deploy"
+  export _AO_HELPER=1
+  exec "$pth_rvmrun" "$nm_ruby" $0 "$pth_rvmrun" "$nm_ruby" "$nm_deployer" "$git_url" "$git_spec" "$cmd_deploy" "$@"
+  echo "ERROR: could not re-exec $0 under $pth_rvmrun $nm_ruby"
+  exit 1
+fi
+
+crumb "start bin/remote-helper"  
+
+unset cd # disable rvm's cd function to prevent prompts
+
+git_branch=$(echo $git_spec | cut -d: -f1)
+git_sha=$(echo $git_spec | cut -d: -f2)
 
 mkdir -p "$HOME/.deploy/$nm_deployer"
 cd "$HOME/.deploy/$nm_deployer"
@@ -61,4 +62,4 @@ git submodule -q update --init --recursive
 crumb "executing bin/$cmd_deploy $@"
 export AO_USER="$nm_deployer"
 bin/$cmd_deploy "$@"
-crumb "done"
+crumb "end bin/remote-helper"
