generalize local-gem, gempush, gemserver into edit, push, server vocabulary

diff --git a/bin/server b/bin/server
--- a/bin/server
+++ b/bin/server
@@ -1,10 +1,10 @@
 #!/bin/bash
 
 #/ NAME
-#/     local-gemserver -- runs geminabox locally
+#/     server -- runs geminabox
 #/
 #/ SYNOPSIS
-#/     local-gemserver
+#/     server gem
 
 # figure out the project root under which bin, lib live
 shome="$(cd -P -- "$(dirname -- "$0")/.." && pwd -P)"
@@ -14,6 +14,21 @@ source "$shome/bin/_prime" "$@"
 
 # entry point
 function main {
+  nm_component="$1"; shift
+
+  case "$nm_component" in 
+    gem)
+      server_gem "$@"
+      ;;
+    *)
+      logger_fatal "don't know how to run ${nm_component}"
+      exit 1
+      ;;
+  esac
+}
+
+# run geminabox
+function server_gem {
   rackup "$shome/config/config.ru"
 }
 
@@ -24,6 +39,10 @@ function main {
 parse_command_line "$@" || exit $?
 eval set -- "${FLAGS_ARGV}"
 
+if [[ "$#" < 1 ]]; then
+  logger_fatal "missing component(s)"
+  exit 1
+fi
+
 # pass arguments to entry point
 main "$@"
-
